apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-sora-setting
spec:
  forms:
    - group: general
      label: 基本设置
      formSchema:
        - $formkit: attachment
          name: avatar
          label: 头像
        - $formkit: radio
          name: rss
          label: RSS
          value: 1
          options:
            - label: 开启
              value: 1
            - label: 关闭
              value: 0

    - group: comment
      label: 评论
      formSchema:
        - $formkit: group
          name: Artalk
          label: Artalk
          children:
            - $formkit: radio
              name: enable
              label: 开启 Artalk 评论
              value: 0
              options:
                - label: 开启
                  value: 1
                - label: 关闭
                  value: 0
            - $formkit: text
              name: site
              label: 站点名
            - $formkit: text
              name: server
              label: Artalk 后端地址

    - group: social
      label: 社交媒体
      formSchema:
        - $formkit: repeater
          name: socials
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: name
              label: 名称
              clearable: true
              searchable: true
              validation: "required"
              options:
                - label: BiliBili
                  value: bilibili
                - label: Email
                  value: email
                - label: Facebook
                  value: facebook
                - label: GitHub
                  value: github
                - label: Instagram
                  value: instagram
                - label: QQ
                  value: qq
                - label: Telegram
                  value: telegram
                - label: TikTok
                  value: tiktok
                - label: Twitter/X
                  value: twitter
                - label: YouTube
                  value: youtube
                - label: 微博
                  value: weibo
                - label: 小红书
                  value: xiaohongshu
                - label: 知乎
                  value: zhihu
            - $formkit: text
              name: url
              label: 地址
              validation: "required"

    - group: footer
      label: 页脚
      formSchema:
        - $formkit: group
          name: copyright
          label: 版权
          children:
            - $formkit: text
              name: time
              label: 建站时间
            - $formkit: text
              name: author
              label: 版权所有者

    - group: post
      label: 文章页
      formSchema:
        - $formkit: group
          name: copyright
          label: 版权许可
          children:
            - $formkit: checkbox
              name: license
              label: CC 许可
              options:
                - label: BY
                  value: by
                - label: NC
                  value: nc
                - label: SA
                  value: sa
                - label: ND
                  value: nd
            - $formkit: text
              name: link
              label: 许可链接
